update-frequency: 1
messages:
    history:
        no-history: "<green>There is no history for <white><0></white>!"
        history:
            header: "<gray>History for <white><0></white>:"
            entry:
                kick: "<gray>  - Kicked by <white><0></white> at <white><1></white>. Reason: <white><2></white>."
                mute:
                    permanent: "<gray>  - Muted by <white><0></white> at <white><1></white>. Reason: <white><2></white>."
                    temporary: "<gray>  - Muted by <white><0></white> at <white><1></white> for <white><2></white>. Reason: <white><3></white>."
                ban:
                    permanent: "<gray>  - Banned by <white><0></white> at <white><1></white>. Reason: <white><2></white>."
                    temporary: "<gray>  - Banned by <white><0></white> at <white><1></white> for <white><2></white>. Reason: <white><3></white>."
                ipban: "<gray>  - IP banned by <white><0></white> at <white><1></white>. Reason: <white><2></white>."
    kick:
        failed:
            self: "<red>You cannot kick yourself!"
        sender:
            with-reason: "<red>You have kicked <white><0></white> for <white><1></white>!"
            without-reason: "<red>You have kicked <white><0></white>!"
        receiver:
            with-reason: "<red>You have been kicked by <white><0></white> for <white><1></white>!"
            without-reason: "<red>You have been kicked by <white><0></white>!"
    mute:
        failed:
            already-muted: "<red><0> is already muted!"
            self: "<red>You cannot mute yourself!"
        sender:
            permanent:
                with-reason: "<red>You have muted <white><0></white> for <white><1></white>!"
                without-reason: "<red>You have muted <white><0></white>!"
            temporary:
                with-reason: "<red>You have muted <white><0></white> for <white><1></white> for <white><2></white>!"
                without-reason: "<red>You have muted <white><0></white> for <white><1></white>!"
        receiver:
            permanent:
                with-reason:
                    command: "<red>You have been muted by <white><0></white> for <white><1></white>."
                    chat: "<red>You are currently muted by <white><0></white> for <white><1></white>."
                without-reason:
                    command: "<red>You have been muted by <white><0></white>."
                    chat: "<red>You are currently muted by <white><0></white>."
            temporary:
                with-reason:
                    command: "<red>You have been muted by <white><0></white> for <white><1></white>. This expires in <white><2></white>."
                    chat: "<red>You are currently muted by <white><0></white> for <white><1></white>. This expires in <white><2></white>."
                without-reason:
                    command: "<red>You have been muted by <white><0></white>. This expires in <white><1></white>."
                    chat: "<red>You are currently muted by <white><0></white>. This expires in <white><1></white>."
                expired: "<green>Your mute has expired!"
    unmute:
        failed:
            not-muted: "<red><0> is not muted!"
        sender: "<green>You have unmuted <white><0></white>!"
        receiver: "<green>You have been unmuted by <white><0></white>!"
    ban:
        failed:
            already-banned: "<red><0> is already banned!"
            self: "<red>You cannot ban yourself!"
        sender:
            permanent:
                with-reason: "<red>You have banned <white><0></white> for <white><1></white>!"
                without-reason: "<red>You have banned <white><0></white>!"
            temporary:
                with-reason: "<red>You have banned <white><0></white> for <white><1></white> for <white><2></white>!"
                without-reason: "<red>You have banned <white><0></white> for <white><1></white>!"
        receiver:
            permanent:
                with-reason:
                    command: "<red>You have been banned by <white><0></white> for <white><1></white>."
                    login: "<red>You are currently banned by <white><0></white> for <white><1></white>."
                without-reason:
                    command: "<red>You have been banned by <white><0></white>."
                    login: "<red>You are currently banned by <white><0></white>."
            temporary:
                with-reason:
                    command: "<red>You have been banned by <white><0></white> for <white><1></white>.\nThis expires in <white><2></white>."
                    login: "<red>You are currently banned by <white><0></white> for <white><1></white>.\nThis expires in <white><2></white>."
                without-reason:
                    command: "<red>You have been banned by <white><0></white>.\nThis expires in <white><1></white>."
                    login: "<red>You are currently banned by <white><0></white>.\nThis expires in <white><1></white>."
    ipban:
        failed:
            already-banned: "<red><0> is already banned!"
            self: "<red>You cannot ban yourself!"
        sender:
            with-reason: "<red>You have IP banned <white><0></white> for <white><1></white>!"
            without-reason: "<red>You have IP banned <white><0></white>!"
        receiver:
            with-reason:
                command: "<red>You have been banned by <white><0></white> for <white><1></white>."
                login: "<red>You are currently IP banned by <white><0></white> for <white><1></white>."
            without-reason:
                command: "<red>You have been banned by <white><0></white>."
                login: "<red>You are currently IP banned by <white><0></white>."
    unban:
        failed:
            not-banned: "<red><0> is not banned!"
        sender: "<green>You have unbanned <white><0></white>!"
